### ISSUE TITLE
Generate headless schema based on site configuration (available apps) and redeployment of any of these apps

### ISSUE THREAD

**Issue by alansemenov** [enonic/starter-headless#15]
As of now, headless schema is generated once (on app startup) so any changes done to types in the app won't be reflected after the app is redeployed. The same issue happens whenever user adds application(s) to or removes application(s) from the site - the schema will not be updated with the new changes.
To solve this we should regenerate schema on app redeploy and whenever site config is updated.

**Comment by sigdestad** [comment]
This is strange, app redeploy == stop and start? How does this not trigger rebuild of the schema?

**Comment by anatol-sialitski** [comment]
Yes, you are right. If app is redeployed a schema will be updated.
In this task we should focus on update/re-create a schema when any app was added or removed from the site and to generate types based on apps from site configs, not only current app.

**Comment by alansemenov** [comment]
How will we handle a case when one of the apps (with new schema changes) assigned to the site was redeployed? If we only track when apps are added/removed then this will not solve this case.

**Comment by anatol-sialitski** [comment]
Ah, we are talking about an app which added to site, not about an app which based on headless-starter. 
Then a description of the issue is correct. Sorry for confusing.

**Comment by sigdestad** [comment]
Ok, maybe the title should be updated then.

However, currently we don't load CTY's from any other apps at all - using the headless starter. So I don't see how this task is relevant at all?

**Comment by sigdestad** [comment]
Oh.. maybe this actually _is_ the task about generally being able to pickup changes from other apps? PLS consider the task titles more carefully in the future.

**Comment by alansemenov** [comment]
We might separate this into two different tasks if that's the problem, but I think the two problems are very related. In both cases you regenerate schema on event.

**Comment by sigdestad** [comment]
Sure, as many tasks as you like. My point is essentially that this task title does not make any sense?

**Comment by alansemenov** [comment]
Feel free to update :)

**Comment by anatol-sialitski** [comment]
will be done on lib-guillotine side
